### ISSUE TITLE
typing ng- doesn't show autocomplete options

### ISSUE THREAD

**Issue by abtx** [ognjenjevremovic/atom-angularjs-snippets#1]
It doesn't output any of the snippets, unfortunately.

**Comment by ognjenjevremovic** [comment]
Can you please elaborate a bit more?

I've just tested it out and it works as it should.
Here is the screenshot:
<img width="310" alt="ng- preview" src="https://cloud.githubusercontent.com/assets/14274816/23097810/f1f61940-f63e-11e6-9fb2-9c3f4f9bec4c.png">

This package provides the snippets for the **_JS_** files.
It does not contain the _HTML attribute/element directives however_.

_Also, I should mention that the snippets work from within **script** tag in HTML too:_
<img width="692" alt="ng- preview from html" src="https://cloud.githubusercontent.com/assets/14274816/23097827/6d13a0a2-f63f-11e6-89ec-2690539a829b.png">

**Comment by ognjenjevremovic** [comment]
## **Issue closed**

There seams to be no problem with the plugin whatsoever; or at least, I can not reproduce it.
If someone experiences the same issue in the future, please **submit a new ticket**.
